namespace: pro-jf-zgz-emergency-map-front
replicaCount: 2
registry: harbor.server.local/danielbeltejar/zgz-emergency-map-frontend
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
extraEnv:
- name: "TZ"
  value: "UTC"
- name: "API_URL"
  value: "https://api.zgz-emergency-map.juanfranciscoperez.es"
extraEnvFrom:
- secretRef:
    name: frontend-secrets
resources:
  requests:
    memory: "64Mi"
    cpu: 100m
  limits:
    cpu: 500m
    memory: "256Mi"
volumes:
- name: tmpfs-var-lib-nginx-tmp
  emptyDir:
    medium: Memory
- name: tmpfs-run-nginx
  emptyDir:
    medium: Memory
volumeMounts:
- name: tmpfs-var-lib-nginx-tmp
  mountPath: /var/lib/nginx/tmp
- name: tmpfs-run-nginx
  mountPath: /run/nginx
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-juanfran
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-set-header: X-Real-IP $remote_addr
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  class: "nginx-online"
  host: "zgz-emergency-map.juanfranciscoperez.es"
  tls: true
